set search_path = public;

create table if not exists public.users (
  id integer generated by default as identity primary key,
  auth_user_id varchar(255) not null,
  email varchar(320) not null,
  role varchar(50) not null default 'team_member',
  is_active boolean not null default true,
  created_at timestamp without time zone not null default (now() at time zone 'utc'),
  updated_at timestamp without time zone not null default (now() at time zone 'utc'),
  constraint users_role_check
    check (role in ('team_member', 'team_analyst', 'admin'))
);

create unique index if not exists uq_users_auth_user_id
  on public.users (auth_user_id);

create unique index if not exists uq_users_email
  on public.users (email);

create index if not exists ix_users_id
  on public.users (id);

create or replace function public.set_users_updated_at()
returns trigger as $$
begin
  new.updated_at = now() at time zone 'utc';
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_users_updated_at on public.users;

create trigger set_users_updated_at
before update on public.users
for each row execute procedure public.set_users_updated_at();

grant all on table public.users to service_role;
