set search_path = public;

-- Rename calls table to stoppages (data preserved)
alter table if exists public.calls rename to stoppages;

do $$
begin
  if exists (
    select 1 from pg_class
    where relkind = 'S' and relname = 'calls_id_seq'
  ) then
    alter sequence public.calls_id_seq rename to stoppages_id_seq;
  end if;
end $$;

alter table if exists public.stoppages
  alter column id set default nextval('public.stoppages_id_seq'::regclass);

alter sequence if exists public.stoppages_id_seq owned by public.stoppages.id;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'calls_pkey'
  ) then
    alter table public.stoppages rename constraint calls_pkey to stoppages_pkey;
  end if;

  if exists (
    select 1 from pg_constraint
    where conname = 'calls_point_id_fkey'
  ) then
    alter table public.stoppages rename constraint calls_point_id_fkey to stoppages_point_id_fkey;
  end if;
end $$;

alter index if exists public.ix_calls_id rename to ix_stoppages_id;

-- Add stoppage_type with backward-compatible default
alter table public.stoppages
  add column if not exists stoppage_type text;

update public.stoppages
set stoppage_type = 'call'
where stoppage_type is null;

alter table public.stoppages
  alter column stoppage_type set default 'call',
  alter column stoppage_type set not null;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'stoppages_stoppage_type_check'
  ) then
    alter table public.stoppages drop constraint stoppages_stoppage_type_check;
  end if;

  alter table public.stoppages
    add constraint stoppages_stoppage_type_check
    check (stoppage_type in ('call', 'injury', 'timeout', 'other'));
end $$;

create index if not exists idx_stoppages_point_time
  on public.stoppages (point_id, call_timestamp);

-- Halftime marker table (max one halftime per game)
create table if not exists public.halftimes (
  id integer generated by default as identity primary key,
  game_id integer not null references public.games(id) on delete cascade,
  halftime_timestamp timestamp without time zone not null,
  comments text,
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create unique index if not exists uq_halftimes_game_id
  on public.halftimes (game_id);

create index if not exists ix_halftimes_id
  on public.halftimes (id);

grant all on table public.stoppages to anon;
grant all on table public.stoppages to authenticated;
grant all on table public.stoppages to service_role;

grant all on table public.halftimes to anon;
grant all on table public.halftimes to authenticated;
grant all on table public.halftimes to service_role;
